### ISSUE TITLE
[BUG] Victoria Unable To Consistently Install In Ubuntu

### ISSUE THREAD

**Issue by JMoulderGW** [glasswall-sre/victoria_email#65] opened 2021-06-02 11:16 UTC
**Description**
Victoria Email plug-in is unable to consistently install

**Reproduction Steps**
Steps to reproduce the behaviour in Ubuntu:

```
# Update Ubuntu Repos and Upgrade the OS/Applications
apt update && apt upgrade -y

# Install Pre-requisites
apt install -y \
curl \
vim \
python3 \
python3-pip

# Install Azure CLI
curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Install Victoria
pip3 install \
victoria \
victoria_rebuilder \
victoria_email

# Log into Azure
az login

# Create or copy Victoria Config file

# Run the Victoria Help command
victoria -h
```

**Expected behavior**
When running the Victoria Help command you should receive the following output:-
```
josh@Glasswall-Josh:~$ victoria
Usage: victoria [OPTIONS] COMMAND [ARGS]...

 V.I.C.T.O.R.I.A.

 Very
 Important
 Commands for
 Toil
 Optimization:
 Reducing
 Inessential
 Activities

 Victoria is the SRE toolbelt -- a single command with multiple pluggable
 subcommands for automating any number of 'toil' tasks that inhibit SRE
 productivity.

Options:
  -c, --config-file FILE  The config file to load.
  --version               Show the version and exit.
  -h, --help              Show this message and exit.

Commands:
  config     Print the loaded config, and the path to the default config...
  email      Perform various actions on the Rebuild for Email platform.
  encrypt    Envelope encrypt data easily.
  rebuilder  The Rebuilder allows the rebuilding of environments via CLI.
  store      Store files/data in cloud storage.
```

**Current Behaviour**
```
root@fe68d2197cab:/# victoria -h
No module named 'packaging'
No module named 'packaging'
Traceback (most recent call last):
  File "/usr/local/bin/victoria", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/victoria/script/victoria.py", line 108, in main
    cli.main(obj=cfg)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1061, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 923, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1624, in parse_args
    rest = super().parse_args(ctx, args)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1379, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 2364, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 2326, in process_value
    value = self.callback(ctx, self, value)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1279, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 704, in get_help
    return self.command.get_help(self)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1304, in get_help
    self.format_help(ctx, formatter)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1335, in format_help
    self.format_options(ctx, formatter)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1533, in format_options
    self.format_commands(ctx, formatter)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1597, in format_commands
    cmd = self.get_command(ctx, subcommand)
  File "/usr/local/lib/python3.8/dist-packages/victoria/script/victoria.py", line 62, in get_command
    cfg = config.load_plugin_config(plgn, ctx.obj)
  File "/usr/local/lib/python3.8/dist-packages/victoria/config.py", line 240, in load_plugin_config
    loaded_config = plugin.config_schema.load(raw_config)
  File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 714, in load
    return self._do_load(
  File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 848, in _do_load
    result = self._deserialize(
  File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 656, in _deserialize
    value = self._call_and_store(
  File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 488, in _call_and_store
    value = getter_func(data)
  File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 653, in <lambda>
    getter = lambda val: field_obj.deserialize(
  File "/usr/local/lib/python3.8/dist-packages/marshmallow/fields.py", line 344, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/marshmallow/fields.py", line 591, in _deserialize
    return self._load(value, data, partial=partial)
  File "/usr/local/lib/python3.8/dist-packages/marshmallow/fields.py", line 574, in _load
    valid_data = self.schema.load(value, unknown=self.unknown, partial=partial)
TypeError: 'Nested' object is not callable
```

**Platform:**
 - OS: Ubuntu 20.04
 - Shell: Bash
 - Victoria version: 1.0.1
 - Python version: 3.6+

**Comment by mukulgupta2138** [comment] 2021-06-07 13:51
The issue is being created by updated package of _marshmallow_ . Try to downgrade the marshmallow package to **pip3 install 'marshmallow==3.11.1' --force-reinstall**  and see if it works fine for you ?

This new package was released in May and this wouldn't have been working for users who installed the package after that
![image](https://user-images.githubusercontent.com/77505708/121028579-95c2fa00-c7c5-11eb-8599-cacb61655f8c.png)

**Comment by mukulgupta2138** [comment] 2021-06-08 07:14
This is now fixed, marking as resolved

**Closed by mukulgupta2138** 2021-06-08 07:14 UTC
Labels: bug
